name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Build Watch App
      run: |
        xcodebuild build \
          -project RuuviTempWatch.xcodeproj \
          -scheme "RuuviTempWatch Watch App" \
          -destination "platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)" \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
          
    - name: Run Tests
      run: |
        xcodebuild test \
          -project RuuviTempWatch.xcodeproj \
          -scheme "RuuviTempWatch Watch App" \
          -destination "platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)" \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO